spring:
  datasource:
    password: root@123
    url: jdbc:mysql://localhost:3306/shweta
    username: root
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
